server:
  port: 8081
spring:
  application:
    name: "requests"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "${SPRING_R2DBC_HOST_REQUEST:localhost}"
    port: "${SPRING_R2DBC_PORT_REQUEST:5432}"
    database: "${SPRING_R2DBC_DATABASE_REQUEST:requests}"
    schema: "public"
    username: "${SPRING_R2DBC_USERNAME_REQUEST:sm}"
    password: "${SPRING_R2DBC_PASSWORD_REQUEST:1234}"
adapter:
  restconsumer:
    timeout: 5000
    url: "${AUTH_SERVICE_URL:http://localhost:8080}"
  sqs:
    region: "${MY_AWS_REGION:us-east-1}"
    queueUrl: "${AWS_SQS_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225422344476/loan-decisions-queue}"
    capacityValidationQueueUrl: "${AWS_SQS_CAPACITY_VALIDATION_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225422344476/loan-capacity-validation-request-queue}"
    approvedLoanQueueUrl: "${AWS_SQS_APPROVED_LOAN_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225422344476/loan-approved-queue}"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"
routes:
  paths:
    loans: "/api/v1/loans"
    loansForReview: "/api/v1/loansForReview"
    loanDecision: "/api/v1/loans/{id}/decision"
security:
  jwt:
    keys-location:
      public: "${JWT_PUBLIC_KEY:classpath:keys/public_key.pem}"
entrypoint:
  sqs:
    region: "${MY_AWS_REGION:us-east-1}"
    queueUrl: "${AWS_SQS_CAPACITY_VALIDATION_RESPONSE_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225422344476/loan-capacity-validation-response-queue}"
    waitTimeSeconds: "20"
    maxNumberOfMessages: "10"
    visibilityTimeoutSeconds: "10"
    numberOfThreads: "1"