server:
  port: 8081
spring:
  application:
    name: "requests"
  devtools:
    add-properties: false
  profiles:
    include: null

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "requests"
    schema: "public"
    username: "sm"
    password: "1234"

adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"

routes:
  paths:
    loans: "/api/v1/loans"
    LoansForReview: "/api/v1/loansForReview"

security:
  jwt:
    keys-location:
      public: classpath:keys/public_key.pem

